name: Deploy Preview

on:
  workflow_dispatch:

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ./.node-version
          cache: "npm"
      - run: npm ci

      - run: npm run build

      - name: Deploy pages preview
        id: deploy-pages-preview
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: pages deploy ./dist --branch="${{ github.head_ref }}"
