name: Deploy Preview

on:
  workflow_dispatch:
  pull_request:

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    outputs:
      pages-deployment-alias-url: ${{ steps.deploy-pages-preview.outputs.pages-deployment-alias-url }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ./.node-version
          cache: "npm"
      - run: npm ci

      - run: npm run build

      - name: Deploy pages preview
        id: deploy-pages-preview
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: pages deploy ./dist --branch="${{ github.head_ref }}"

  add-comment:
    runs-on: ubuntu-slim
    if: github.event_name == 'pull_request'
    needs: [deploy-preview]
    steps:
      - name: Find Comment
        uses: peter-evans/find-comment@v3
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "github-actions[bot]"
          body-includes: Deploy pages preview

      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v5
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Deploy pages preview
            - Deployment alias URL: ${{ needs.deploy-preview.outputs.pages-deployment-alias-url }}
          edit-mode: replace
